# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("lptester", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
